"""password lengths updated

Revision ID: 07524eb5e149
Revises: baf5147f0922
Create Date: 2021-11-29 14:58:33.482955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07524eb5e149'
down_revision = 'baf5147f0922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
