"""edit decimal field in money model

Revision ID: 099a88bb9a44
Revises: 2157835da788
Create Date: 2021-12-29 11:32:58.560495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099a88bb9a44'
down_revision = '2157835da788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('money', 'amount',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.DECIMAL(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('money', 'amount',
               existing_type=sa.DECIMAL(precision=6, scale=2),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
