"""calorie model fixed

Revision ID: 3d7da76f7950
Revises: 5326b7b3bfba
Create Date: 2022-01-19 10:42:53.042577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d7da76f7950'
down_revision = '5326b7b3bfba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calories', 'unit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calories', sa.Column('unit', postgresql.ENUM('gram', 'portion', name='unit'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
