"""Money Model upgrade

Revision ID: 54b015f59233
Revises: a8f8fd652b32
Create Date: 2021-12-23 10:33:53.436417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b015f59233'
down_revision = 'a8f8fd652b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('money', sa.Column('is_regular', sa.Boolean(), nullable=False))
    op.add_column('money', sa.Column('title', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('money', 'title')
    op.drop_column('money', 'is_regular')
    # ### end Alembic commands ###
