"""password length updated

Revision ID: 8e0315173d60
Revises: 3f95b0b229d5
Create Date: 2021-11-29 14:42:32.645454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0315173d60'
down_revision = '3f95b0b229d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
