"""Money Model

Revision ID: a8f8fd652b32
Revises: dc6cd389e341
Create Date: 2021-12-22 15:47:03.474991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f8fd652b32'
down_revision = 'dc6cd389e341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('income', 'outlay', name='moneytype'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=2), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_id'), 'money', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_money_id'), table_name='money')
    op.drop_table('money')
    # ### end Alembic commands ###
