"""lengths updated

Revision ID: baf5147f0922
Revises: 8e0315173d60
Create Date: 2021-11-29 14:44:43.625871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf5147f0922'
down_revision = '8e0315173d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
