"""calorie model fixed

Revision ID: f760637dded0
Revises: cc87b02bc995
Create Date: 2022-01-19 17:42:38.468671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f760637dded0'
down_revision = 'cc87b02bc995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calories', sa.Column('dish_id', sa.Integer(), nullable=False))
    op.add_column('calories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'calories', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'calories', 'dishes', ['dish_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calories', type_='foreignkey')
    op.drop_constraint(None, 'calories', type_='foreignkey')
    op.drop_column('calories', 'user_id')
    op.drop_column('calories', 'dish_id')
    # ### end Alembic commands ###
